# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bebe9098431521590013982c0b1c055c6ba1d9b4b56eab29ed53a2d531ed00071d9415c9f78f1073b0cfcd124e6c42ccb80a6f68fc318ea266d36850561360f3

test:
  secret_key_base: 5d717956e4ef467688d2d5cbaebd8aceafe070b2c9f7fd2f018807bb4925e7e4b407f89bc9cb3142b8d843ca5ae0819138e11f189fff2fe8d8522cf504b36f1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
